MUL-1242
arkivverket/bevaring-cli pull request #4
Opened 2022-10-18 08:02 UTC by PawelMatrasArkivverket

2022-10-18 08:10 UTC, omBratteng reviewed
Her var det mye refaktorering, hva er begrunnelsen for det?
MOL-1242, ikke MUL-1242

Fra MOL-1062:
> CLI må lagre IAM-credentials til en ny profil i “.aws”-mappen.

2022-10-31 14:36 UTC, omBratteng requested changes
Jeg er ikke enig at dette er en nødvendig refaktorering av koden, samt vi har ikke blitt enig på teamet at det er noe vi ønsker. Du kan ikke bare snikinnøfre slikt.

Typer ble valgt fordi det ligner veldig på hvordan FastAPI, så disse endringene gjør at vi går bort fra den måten å skrive endepunkter/ kommandoer på.

Det fungerer ikke å installere CLI og kjøre `bevaring`, eller noen under kommandoer.

2022-10-31 14:36 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +                aws_access_key_id = {json['iam_secret_access_key']}
Det er ikke lurt å skrive til `default`, det kan få uønskede endringer, f.eks slette credentials som vi ikke har injected.
Ville også ha brukt https://docs.python.org/3/library/configparser.html#configparser.RawConfigParser.add_section for å parse aws filen, og legge til ny section, hvor tittel f.eks er Session ID

2022-10-31 14:36 UTC, omBratteng commented on bevaring_cli/main.py
> +    return assemble(all_cmds)
Jeg er ikke enig at dette er en nødvendig refaktorering av koden, samt vi har ikke blitt enig på teamet at det er noe vi ønsker. Du kan ikke bare snikinnøfre slikt.

2022-10-31 14:36 UTC, omBratteng commented on bevaring_cli/commands/cmd.py
> +        self._app()
Jeg er ikke enig at dette er en nødvendig refaktorering av koden, samt vi har ikke blitt enig på teamet at det er noe vi ønsker. Du kan ikke bare snikinnøfre slikt.

2022-10-31 14:36 UTC, omBratteng commented on bevaring_cli/commands/auth.py
> +                 "that does not have a browser installed.",
Vi splitter ikke tekst over flere linjer

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/auth.py
> +log = logging.getLogger(__name__)
Renamed.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/__init__.py
> +del path, glob
Det er python måte å sikre på at import * virker uten at man må liste opp alle filer som skal med. Kjekt å ha for å slippe å måte hardcode hvilken commands som skal med i applikasjonen. Men kan også gjøres på annen måte.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/auth.py
> +                 "that does not have a browser installed.",
Flame/lint masser på at linja var for langt.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/cmd.py
> +        self._app()
Hva som må til for å har håp for å kunne endre meningen din?
DI er standard i software utvikling. Jeg har ikke hardwired applikasjoner (slik det gjøres i prosjektet) på minst 15 år. Softwaren blir mye enklere. Ingen settings.py, statiske og/eller globale contexter/variabler eller slenging av mange services ned callstacken slik det er f.eks. bevaring-arkiv-service. Og mye mer.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +                aws_access_key_id = {json['iam_secret_access_key']}
Av den grunn har jeg foreslått på slack alternative design som er enklere og mindre riskofritt. Vi muligjør for brukeren å styre aws-cli via environment variabler ved å legge til en "aws-cli" command som printer ut:
```
export AWS_REGION=oslo
export AWS_KEY...=ABC
export AWS_SECRET...=DEF
```
Brukeren da kan source det direkte eller via copy&paste og kjøre aws-cli. Vi vil ikke herpe til brukerens aws-cli settup. Det gir oss også løsere kobling mot aws-cli.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/exceptions.py
> +class AuthenticationError(Exception):
Alle exceptions resulterer i exit. Jeg har endret det for å kunne legge til årsaken til feilen (message), noe Exit ikke har.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/main.py
> +file_handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s: %(message)s"))
Jobber man på cli er det altid kjekkt å ha i min mening. Både for deg selv for å ha historikken på hva som skjedde og også når vi skal hjelpe noen.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/main.py
> -        state["endpoint"] = endpoint
Ikke nødvendigvis. Vi kan legge det til global også. Tenkte at det er bedre å ha det eksplisit. Endpoint er ikke global heller. Når "bevaring help" eller "bevaring auth" har den ikke.

2022-11-01 15:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/main.py
> +    return assemble(all_cmds)
Av den grunn har jeg lagt det som en diskusjonspunkt på slack: persistering av session. Om det er det du mener med kommentaren din.

2022-11-01 16:08 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +                aws_access_key_id = {json['iam_secret_access_key']}
Det er flere applikasjoner som benytter seg av `~/.aws/credentials`, så den er regnet som ett standard sted å lagre IAM credentials, og ikke bare for `aws-cli`.

2022-11-07 11:01 UTC, PawelMatrasArkivverket commented on app.toml
> +iam_secret_access_key = ''
Koden er nå tilpasset til å laste opp app.toml fra samme katalogen som main.py er i. Så det er en del av leveransen og bevaring cli kan kjøres fra hvilken som helst katalog.

2022-11-08 14:28 UTC, PawelMatrasArkivverket commented on bevaring_cli/__init__.py
> -BEVARING_CLI_CLIENT_ID = "d18685f9-148d-4e9a-98b3-194bcd01bc95"
Hardcode det tilbake.

2022-11-08 14:33 UTC, PawelMatrasArkivverket commented on bevaring_cli/main.py
> +file_handler.setFormatter(logging.Formatter("%(asctime)s %(levelname)s: %(message)s"))
Flytt til config mappa.

2022-11-08 14:35 UTC, PawelMatrasArkivverket commented on bevaring_cli/exceptions.py
> +class AuthenticationError(Exception):
Add error code parameter og bruke den ved exit.

2022-11-08 14:37 UTC, PawelMatrasArkivverket commented on bevaring_cli/main.py
> -        state["endpoint"] = endpoint
Lage varsel på at brukeren ikke kjører i prod.

2022-11-08 14:39 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +                aws_access_key_id = {json['iam_secret_access_key']}
Addere opsjon for å genere export eller inn i ~/.aws/ (som vi fikser senere i eget issue).

2022-11-08 14:40 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +                aws_access_key_id = {json['iam_secret_access_key']}
Addere opsjon for å genere export eller inn i ~/.aws/ (som vi fikser senere i eget issue).

2022-11-10 11:51 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +                aws_access_key_id = {json['iam_secret_access_key']}
https://arkivverket.atlassian.net/jira/software/c/projects/MOL/boards/168?modal=detail&selectedIssue=MOL-1411 
fikser det.

2022-11-14 07:46 UTC, omBratteng approved these changes

2022-11-14 07:46 UTC, merged