MOL-1366 Utvid CLI til å laste ned ip0
arkivverket/bevaring-cli pull request #5
Opened 2022-11-16 09:23 UTC by EivindRydningen

2022-11-16 14:26 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +            copy_credentials_id = str(current_highest_index + 1)
Snakka vi ikke om å gjøre det slik
```
  id = 0
  while str(id) in existing_ids:
    ++id
```
Det vil fylle eventuelle hull.

2022-11-16 14:26 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +    def get_new_credentials_id(id: str, existing_ids: List[str]):
Når man programmerer må man være presiss. "get" er ordet med flest betydninger og derfor er ikke presis.
next_id, create_id, unique_id eller lignende er det.

2022-11-16 14:26 UTC, PawelMatrasArkivverket commented on tests/conftest.py
> +            "ver": "2.0",
?

2022-11-16 14:26 UTC, PawelMatrasArkivverket commented on bevaring_cli/commands/datasett.py
> +                raise FileNotFoundError("No copy credentials file exists.")
Det er ikke noe feil situasjon. Det er forventet. Så skal man bare ikke printe noe i starten.
Eller kanskje bare logge: no copies created yet.

2022-11-16 18:21 UTC, omBratteng commented on tests/conftest.py
> +            "ver": "2.0",
Trailing commas

2022-11-16 18:21 UTC, omBratteng commented on tests/conftest.py
> +        "expires_in": 3899,
Trailing commas

2022-11-17 13:31 UTC, EivindRydningen commented on bevaring_cli/commands/datasett.py
> +        user_has_bucket: bool = Argument(False, help="If user has a target bucket to copy to."),
Det va spesifisert i systemdesign - generasjoner, men det trengs egentlig ikke. Avklart med Snorri og.

2022-11-17 13:31 UTC, EivindRydningen commented on bevaring_cli/commands/datasett.py
> +            copy_credentials_id = str(current_highest_index + 1)
Sant, tror det blir en bra løsning.

2022-11-17 13:34 UTC, EivindRydningen commented on tests/test_datasett.py
> +def test_list_copies_raises_FileNotFoundError_when_no_file_exists(command_input_print_copy_file):
Sant, skal endre i copies funksjonen og tests

2022-11-17 13:43 UTC, omBratteng requested changes
Den menneskelige 🤖  trailing-comma linteren slår til igjen

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +                'receipt_email': receipt_email
```suggestion
                'receipt_email': receipt_email,
```

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +            'iam_secret_access_key': json['iam_secret_access_key']
```suggestion
            'iam_secret_access_key': json['iam_secret_access_key'],
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response
```suggestion
        json=copy_response,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response_with_s3_path
```suggestion
        json=copy_response_with_s3_path,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response
```suggestion
        json=copy_response,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    command_input_index_increment_test
```suggestion
    command_input_index_increment_test,
```

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no")
```suggestion
        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no"),
```

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +        existing_ids = list(copies.keys())
```suggestion
            copies = {}

        existing_ids = list(copies.keys())
```

Visuell splitt

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/datasett.py
> +        id: str = Argument(..., help="Id of the aws credentials to print")
```suggestion
        id: str = Argument(..., help="Id of the aws credentials to print"),
```

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/session.py
> +        self._main.add(self._app, name='session', help="Manages process of new generation creation")
```suggestion
        self._main.add(self._app, name='session', help="Manages process of new generation creation"),
```

2022-11-17 13:43 UTC, omBratteng commented on bevaring_cli/commands/session.py
> +        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no")
```suggestion
        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no"),
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    expected_creds
```suggestion
    expected_creds,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    expected_creds_with_s3_path
```suggestion
    expected_creds_with_s3_path,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    command_input_print_copies_file
```suggestion
    command_input_print_copies_file,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response
```suggestion
        json=copy_response,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    command_input_id
```suggestion
    command_input_id,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response
```suggestion
        json=copy_response,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    command_input_aws_export
```suggestion
    command_input_aws_export,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response
```suggestion
        json=copy_response,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +    command_input_aws_export_id_not_found
```suggestion
    command_input_aws_export_id_not_found,
```

2022-11-17 13:43 UTC, omBratteng commented on tests/test_datasett.py
> +        json=copy_response
```suggestion
        json=copy_response,
```

2022-11-17 14:27 UTC, PawelMatrasArkivverket approved these changes

2022-11-17 14:30 UTC, omBratteng commented on bevaring_cli/commands/session.py
> +        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no"),
Kunne vi hentet default verdien fra faktisk variabel?
```suggestion
        endpoint: str = Option('', help=f"The endpoint to use for the API. Default is {INSERT_VARIABEL_HERE}"),
```

2022-11-17 14:31 UTC, omBratteng commented on tests/test_datasett.py
> +import os
To importer av `os`?

2022-11-17 14:32 UTC, omBratteng requested changes

2022-11-17 14:32 UTC, omBratteng commented on tests/test_datasett.py
> +    expected = "\nalias awsb='aws --endpoint-url https://s3-oslo.arkivverket.no'\nexport AWS_REGION=oslo\nexport AWS_ACCESS_KEY_ID=ik\nexport AWS_SECRET_ACCESS_KEY=is\n\n"
```suggestion
    expected = """
alias awsb='aws --endpoint-url https://s3-oslo.arkivverket.no'
export AWS_REGION=oslo
export AWS_ACCESS_KEY_ID=ik
export AWS_SECRET_ACCESS_KEY=is

"""
```

I stedet for å bruke \n som er lite bra DX, så kan vi bruke `"""` for multiline string (ulempen er at den også får med seg indentering)

2022-11-18 12:59 UTC, EivindRydningen commented on bevaring_cli/commands/session.py
> +        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no"),
Fungere å kalle på endpoint inne i funksjonen, men får ikke helt til å hente fra faktisk variabel.  "Default is <enterprython._inject._Setting object at 0x1069c6d40> " e det nærmeste æ kommer med min forståelse av dependency injection. Kanskje @PawelMatrasArkivverket har et forslag?

2022-11-18 13:29 UTC, EivindRydningen commented on bevaring_cli/commands/session.py
> +        endpoint: str = Option('', help="The endpoint to use for the API. Default is bevaring.digitalarkivet.no"),
Fant en løsning sammen med @PawelMatrasArkivverket

2022-11-18 13:30 UTC, EivindRydningen commented on tests/test_datasett.py
> +    expected = "\nalias awsb='aws --endpoint-url https://s3-oslo.arkivverket.no'\nexport AWS_REGION=oslo\nexport AWS_ACCESS_KEY_ID=ik\nexport AWS_SECRET_ACCESS_KEY=is\n\n"
Kopierte expected returverdi fra debuggern og den outputta på det formatet med \n. Va tildels for enkelhets skyld pluss at æ da e sikker på at det stemme overens. Kan godt gjøre det med multiline da.

2022-12-12 11:09 UTC, PawelMatrasArkivverket approved these changes

2022-12-12 11:20 UTC, merged